    def treepopMenu(self, event):
        self.treemenu = wx.Menu()
        item = event.GetItem()
        self.mailtree.SetFocusedItem(item)
        self.mailtree.SelectItem(item)
        self.treeitem = self.mailtree.GetFocusedItem()
        self.selected = self.mailtree.GetItemData(self.treeitem)
        self.menuopen = wx.MenuItem(self.treemenu, wx.ID_ANY, 'View File')
        self.menuadd = wx.MenuItem(self.treemenu, wx.ID_ANY, 'Add to queue')
        self.selectopen = self.treemenu.Append(self.menuopen)
        self.selectadd = self.treemenu.Append(self.menuadd)
        self.Bind(wx.EVT_MENU, self.openFile, self.selectopen)
        self.Bind(wx.EVT_MENU, self.addFile, self.selectadd)
        self.PopupMenu(self.treemenu)
